import { useEffect, useMemo, useState } from "react";
import { api, type ContentCollection, type ContentRecord } from "../api/client";
import { StatusBanner } from "../components/StatusBanner";

const collections: { id: ContentCollection; label: string }[] = [{ id: "blog", label: "博客" }, { id: "news", label: "资讯" }, { id: "projects", label: "项目" }, { id: "pages", label: "页面" }];
export function ContentListPage({ navigate }: { navigate: (path: string) => void }) {
  const [collection, setCollection] = useState<ContentCollection>("blog"); const [items, setItems] = useState<ContentRecord[]>([]); const [search, setSearch] = useState(""); const [published, setPublished] = useState("all"); const [error, setError] = useState("");
  useEffect(() => { api<{ items: ContentRecord[] }>(`/content?collection=${collection}`).then((data) => { setItems(data.items); setError(""); }).catch((reason) => setError(reason.message)); }, [collection]);
  const filtered = useMemo(() => items.filter((item) => { const haystack = `${item.slug} ${item.metadata.title || ""} ${(item.metadata.tags || []).toString()}`.toLowerCase(); return haystack.includes(search.toLowerCase()) && (published === "all" || String(item.metadata.published !== false) === published); }), [items, search, published]);
  return <section className="admin-page"><header className="page-heading"><div><p className="kicker">Repository content</p><h1>Content</h1></div><button className="button" type="button" onClick={() => navigate(`/content/${collection}/new?draft=1`)}>新建内容</button></header><div className="list-controls"><div className="segmented">{collections.map((item) => <button key={item.id} className={collection === item.id ? "is-selected" : ""} onClick={() => setCollection(item.id)}>{item.label}</button>)}</div><input aria-label="搜索内容" placeholder="搜索标题、标签或 slug" value={search} onChange={(event) => setSearch(event.target.value)} /><select aria-label="发布状态" value={published} onChange={(event) => setPublished(event.target.value)}><option value="all">全部状态</option><option value="true">已发布</option><option value="false">未发布</option></select></div>{error && <StatusBanner tone="error">{error}</StatusBanner>}<div className="content-list">{filtered.map((item) => <button key={item.slug} className="content-row" type="button" onClick={() => navigate(`/content/${collection}/${item.slug}`)}><span><strong>{String(item.metadata.title || item.metadata.name || item.slug)}</strong><small>{item.slug}</small></span><span>{item.metadata.published === false ? "未发布" : "已发布"}</span></button>)}{!error && filtered.length === 0 && <p className="empty-state">当前集合没有匹配内容。</p>}</div></section>;
}
