import { useEffect, useMemo, useState } from "react";
import { api, request, type ContentCollection, type ContentRecord } from "../api/client";
import { ConfirmDialog } from "../components/ConfirmDialog";
import { MarkdownEditor } from "../components/MarkdownEditor";
import { StatusBanner } from "../components/StatusBanner";

const today = new Date().toISOString().slice(0, 10);
function draft(collection: ContentCollection): ContentRecord { return { collection, slug: "", path: "", version: "", metadata: { title: "", date: today, summary: "", tags: [], published: false }, body: "" }; }

export function ContentEditorPage({ collection, slug, isDraft, navigate }: { collection: ContentCollection; slug: string; isDraft: boolean; navigate: (path: string) => void }) {
  const [record, setRecord] = useState<ContentRecord>(() => draft(collection)); const [extra, setExtra] = useState("{}"); const [error, setError] = useState(""); const [saving, setSaving] = useState(false); const [confirmDelete, setConfirmDelete] = useState(false);
  const load = () => { if (isDraft) { setRecord(draft(collection)); return; } api<ContentRecord>(`/content/${collection}/${slug}`).then((data) => { setRecord(data); const { title, date, summary, tags, published, ...rest } = data.metadata; setExtra(JSON.stringify(rest, null, 2)); }).catch((reason) => setError(reason.message)); };
  useEffect(load, [collection, slug, isDraft]);
  const title = String(record.metadata.title || record.metadata.name || ""); const tags = useMemo(() => Array.isArray(record.metadata.tags) ? record.metadata.tags.join(", ") : "", [record.metadata.tags]);
  const save = async (force = false) => { try { setSaving(true); const parsed = JSON.parse(extra || "{}"); const metadata = { ...parsed, ...record.metadata, title, date: String(record.metadata.date || ""), summary: String(record.metadata.summary || ""), tags: tags.split(",").map((tag) => tag.trim()).filter(Boolean), published: record.metadata.published === true }; const body = { slug: record.slug, metadata, body: record.body, version: record.version, force }; const next = isDraft ? await api<ContentRecord>(`/content/${collection}`, request("POST", body)) : await api<ContentRecord>(`/content/${collection}/${slug}`, request("PUT", body)); setRecord(next); setError(""); if (isDraft) navigate(`/content/${collection}/${next.slug}`); } catch (reason) { setError(reason instanceof Error ? reason.message : "保存失败"); } finally { setSaving(false); } };
  const remove = async () => { try { await api(`/content/${collection}/${slug}`, request("DELETE", { version: record.version })); navigate("/content"); } catch (reason) { setError(reason instanceof Error ? reason.message : "删除失败"); } };
  return <section className="admin-page"><header className="page-heading"><div><p className="kicker">{collection}</p><h1>{isDraft ? "新建内容" : "编辑内容"}</h1></div><button className="button button--quiet" type="button" onClick={() => navigate("/content")}>返回列表</button></header>{error && <StatusBanner tone="error">{error}</StatusBanner>}<div className="editor-layout"><section className="metadata-form"><label>Slug<input value={record.slug} disabled={!isDraft} onChange={(event) => setRecord({ ...record, slug: event.target.value.toLowerCase() })} required /></label><label>标题<input value={title} onChange={(event) => setRecord({ ...record, metadata: { ...record.metadata, title: event.target.value } })} required /></label><label>日期<input type="date" value={String(record.metadata.date || "")} onChange={(event) => setRecord({ ...record, metadata: { ...record.metadata, date: event.target.value } })} /></label><label>摘要<textarea value={String(record.metadata.summary || "")} onChange={(event) => setRecord({ ...record, metadata: { ...record.metadata, summary: event.target.value } })} /></label><label>标签<input value={tags} onChange={(event) => setRecord({ ...record, metadata: { ...record.metadata, tags: event.target.value.split(",").map((tag) => tag.trim()).filter(Boolean) } })} /></label><label className="checkbox-label"><input type="checkbox" checked={record.metadata.published === true} onChange={(event) => setRecord({ ...record, metadata: { ...record.metadata, published: event.target.checked } })} />发布</label><label>其他元数据 JSON<textarea className="code-input" value={extra} onChange={(event) => setExtra(event.target.value)} /></label><div className="form-actions"><button className="button" type="button" disabled={saving} onClick={() => save()}>{saving ? "保存中" : "保存"}</button>{!isDraft && <><button className="button button--quiet" type="button" onClick={load}>重新加载</button><button className="button button--quiet" type="button" onClick={() => save(true)}>强制覆盖</button><button className="icon-button icon-button--danger" type="button" title="删除内容" aria-label="删除内容" onClick={() => setConfirmDelete(true)}>×</button></>}</div></section><MarkdownEditor value={record.body} onChange={(body) => setRecord({ ...record, body })} /></div>{confirmDelete && <ConfirmDialog title="删除内容" message="此操作会删除该 Markdown 文件，且无法从后台撤销。" confirmLabel="删除" onCancel={() => setConfirmDelete(false)} onConfirm={remove} />}</section>;
}
