import { useEffect, useState } from "react";
import { api, request } from "../api/client";
import { StatusBanner } from "../components/StatusBanner";

type GitStatus = { branch: string; remote: string; changedFiles: string[] }; type Validation = { ok: boolean; message: string; steps: { command: string; ok: boolean; stdout: string; stderr: string }[] };
export function PublishPage() {
  const [status, setStatus] = useState<GitStatus>(); const [selected, setSelected] = useState<string[]>([]); const [message, setMessage] = useState(""); const [validation, setValidation] = useState<Validation>(); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const load = () => api<GitStatus>("/git/status").then((data) => { setStatus(data); setSelected([]); }).catch((reason) => setError(reason.message)); useEffect(() => { void load(); }, []);
  const validate = async () => { try { setBusy(true); setValidation(undefined); const data = await api<Validation>("/git/validate", request("POST", {})); setValidation(data); } catch (reason) { const message = reason instanceof Error ? reason.message : "校验失败"; setError(message); setValidation({ ok: false, message, steps: [] }); } finally { setBusy(false); } };
  const publish = async () => { try { setBusy(true); await api("/git/publish", request("POST", { paths: selected, message })); setMessage(""); setValidation(undefined); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "推送失败"); } finally { setBusy(false); } };
  return <section className="admin-page"><header className="page-heading"><div><p className="kicker">Git over SSH</p><h1>Publish</h1></div><button className="button button--quiet" type="button" onClick={load}>刷新</button></header>{error && <StatusBanner tone="error">{error}</StatusBanner>}<section className="publish-section"><h2>待提交文件</h2><p className="muted">默认不选择任何文件。</p>{status?.changedFiles.length ? <div className="publish-files">{status.changedFiles.map((path) => <label key={path}><input type="checkbox" checked={selected.includes(path)} onChange={(event) => setSelected((current) => event.target.checked ? [...current, path] : current.filter((item) => item !== path))} />{path}</label>)}</div> : <p className="empty-state">工作树没有可发布改动。</p>}</section><section className="publish-section"><h2>校验</h2><button className="button" type="button" disabled={busy} onClick={validate}>{busy ? "运行中" : "运行完整校验"}</button>{validation && <StatusBanner tone={validation.ok ? "success" : "error"}>{validation.message}</StatusBanner>}<div className="validation-log">{validation?.steps.map((step) => <details key={step.command}><summary>{step.ok ? "通过" : "失败"} · {step.command}</summary><pre>{step.stdout || step.stderr || "无输出"}</pre></details>)}</div></section><section className="publish-section"><h2>提交并推送</h2><label>提交信息<input value={message} maxLength={120} onChange={(event) => setMessage(event.target.value)} placeholder="描述本次内容更新" /></label><div className="form-actions"><button className="button" type="button" disabled={busy || !validation?.ok || !selected.length || !message.trim()} onClick={publish}>提交并推送</button></div></section></section>;
}
